version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Build and Test
          command: |
            # Add your build and test commands here
  notify_discord:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run:
          name: Template
          command: echo
