version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Build and Test
          command: |
            # Add your build and test commands here
  notify_discord:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run:
          name: Send Discord Notification
          command: |
            DISCORD_WEBHOOK_URL="https://discord.com/api/webhooks/1159573098216042576/4rVEPkIisvhOmOiY4E8HOP2R11KwfZRLVfyhJBR1FEFsLSUcxdWhZCxXwR72yvhVEHzu"
            BUILD_NAME="$CIRCLE_JOB"
            MESSAGE="Build $BUILD_NAME completed successfully! :tada:"
            curl -X POST -H "Content-Type: application/json" -d "{\"content\":\"$MESSAGE\"}" $DISCORD_WEBHOOK_URL
