name: Notify on Commit

on:
  push:
    branches:
      - main  # Replace with your main branch name if different

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Send notification
      run: |
        curl -d "Your site has been updated! If this was not you please change your password." ntfy.sh/ElliNet13
