name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Generate sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
          $(find . -type f -name '*.html' -exec bash -c 'printf "<url><loc>https://ellinet13.github.io/$(dirname {})/</loc></url>\n"' \;)
          </urlset>' > sitemap.xml
      
      - name: Commit sitemap
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generate sitemap"
          commit_options: "-a"
