name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install xmllint
        run: sudo apt-get install libxml2-utils
      
      - name: Generate sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          find . -type f -name '*.html' -exec bash -c 'printf "<url><loc>https://ellinet13.github.io/$(dirname {} | sed "s/^\.\///")/</loc></url>\n"' \; >> sitemap.xml
          echo '</urlset>' >> sitemap.xml
      
      - name: Validate sitemap
        run: xmllint --noout sitemap.xml
      
      - name: Commit sitemap
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generate sitemap"
          commit_options: "-a"
